added 60 nouns to the urban.txt file
Mimic-Tools/name-generation pull request #61
Opened 2020-10-24 13:59 UTC by ancasimon

2020-10-24 23:08 UTC, ianfhunter requested changes
Can you remove the final lines?

2020-10-24 23:08 UTC, ianfhunter commented on name-segments/nouns/urban.txt
> +
No trailing spaces

2020-10-24 23:08 UTC, ianfhunter commented on name-segments/nouns/urban.txt
> +bus
```suggestion
```

2020-10-24 23:08 UTC, ianfhunter commented on name-segments/nouns/urban.txt
> +metro
```suggestion
```

2020-10-24 23:08 UTC, ianfhunter commented on name-segments/nouns/urban.txt
> +rail
```suggestion
```

2020-10-24 23:08 UTC, ianfhunter commented on name-segments/nouns/urban.txt
> +tube
```suggestion
```

2020-10-24 23:08 UTC, ianfhunter commented on name-segments/nouns/urban.txt
> +transit
```suggestion
```

2020-10-25 00:40 UTC, ancasimon commented
> Can you remove the final lines?

So sorry about that - you are referring to the empty returns I left at the end of the list, right? Done! Please let me know if you would like to see any other changes! Did the same in the mountain adj file too! 😄  @ianfhunter

2020-10-25 09:55 UTC, ianfhunter commented
I made a commit to remove some words that were too modern for a fantasy setting.
You should be able to get these changes by doing `git pull` and it'll hopefully solve your issue

2020-10-28 03:14 UTC, ancasimon commented
> I made a commit to remove some words that were too modern for a fantasy setting.
> You should be able to get these changes by doing `git pull` and it'll hopefully solve your issue

Done! Thanks for the suggestion @ianfhunter  Please let me know if you need any other changes before merging it!

2020-10-28 07:08 UTC, merged